num_worker: 8
work_dir: ./work_dir/ntu120_hdgcn/cross-label/seen_ashp-att-mlp-loss-111/

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: /home/ubuntu/xj/data/ntu120/NTU120_train_111.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  bone: True

test_feeder_args:
  data_path: /home/ubuntu/xj/data/ntu120/NTU120_seen_test_111.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  bone: True
  debug: False

# model
model: model.ActionOOD.Model
model_args:
  num_class: 111
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d_hierarchy.Graph
  graph_args:
    labeling_mode: 'spatial'
    CoM: 21

#optim
weight_decay: 0.0004
base_lr: 0.1
warm_up_epoch: 5
loss_type: Energy  # 修改loss：CE基础上增加energy score作为优化目标

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 100
nesterov: True
